spring:
    application:
        name: demo_crud_users
    datasource:
        url: jdbc:mysql://localhost:3306/user_manage?createDatabaseIfNotExist=true
        username: root
        password: 123456
    jooq:
        sql-dialect: org.hibernate.dialect.MySQL8Dialect
    jpa:
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        properties:
            hibernate:
                show_sql: true
                format_sql: true